apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
  namespace: w255
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv2
  namespace: w255
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv3
  namespace: w255
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data3"