apiVersion: v1
kind: Service
metadata:
  name: lab3
  namespace: w255
  labels:
    app: lab3
spec:
  type: LoadBalancer
  ports:
  - nodePort: 30080
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: lab3
