apiVersion: v1
kind: Service
metadata:
  name: lab4
  namespace: victorramirez
  labels:
    app: lab4
spec:
  type: LoadBalancer
  ports:
  - nodePort: 30080
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: lab4
